const schemaObjects = {
    tradeFQObjectWithFields:{
        "underlyingSymbol": "TEXT",
        "strike": "NUMERIC",
        "expiry": "INTEGER",
        "dateTime": "INTEGER",
        "putCall": "TEXT",
        "tradeDate": "INTEGER",
        "transactionType": "TEXT",
        "quantity": "NUMERIC",
        "tradePrice": "NUMERIC",
        "tradeMoney": "NUMERIC",
        "proceeds": "NUMERIC",
        "ibCommission": "NUMERIC",
        "netCash": "NUMERIC",
        "cost": "NUMERIC",
        "fifoPnlRealized": "NUMERIC",
        "buySell": "TEXT",
        "holdingPeriodDateTime": "INTEGER",
        "whenRealized": "INTEGER",
        "whenReopened": "INTEGER"
    },

    positionsFQMockObject: {
        "accountId": "U14673520",
        "acctAlias": "MQ - Options",
        "symbol": "AAPL  261218C00250000",
        "description": "AAPL 18DEC26 250 C",
        "underlyingSymbol": "AAPL",
        "strike": "250",
        "expiry": "20261218",
        "putCall": "C",
        "position": "1",
        "positionValue": "1897.5",
        "costBasisPrice": "23.94088174",
        "costBasisMoney": "2394.088174",
        "percentOfNAV": "2.87",
        "fifoPnlUnrealized": "-496.588174"
    },

    openPositions: {
        underlyingSymbol: 'TEXT',
        strike: 'NUMERIC',
        expiry: 'INTEGER',
        contractDescCustom: 'TEXT',
        quantity: 'NUMERIC',
        buyDate: 'INTEGER',
        buyDateTime: 'INTEGER',
        buyPrice: 'NUMERIC',
        buyProceeds: 'NUMERIC',
        buyIbCommission: 'NUMERIC',
        buyNetCash: 'NUMERIC',
        buyTxId: 'TEXT',
    },

    closedPositions: {
        underlyingSymbol: 'TEXT',
        strike: 'NUMERIC',
        expiry: 'INTEGER',
        contractDescCustom: 'TEXT',
        quantity: 'NUMERIC',
        buyDate: 'INTEGER',
        buyDateTime: 'INTEGER',
        buyPrice: 'NUMERIC',
        buyPriceAdjusted: 'NUMERIC',
        buyProceeds: 'NUMERIC',
        buyProceedsAdjusted: 'NUMERIC',
        buyIbCommission: 'NUMERIC',
        buyIbCommissionAdjusted: 'NUMERIC',
        buyNetCash: 'NUMERIC',
        buyNetCashAdjusted: 'NUMERIC',
        buyTxId: 'TEXT',
        sellDate: 'INTEGER',
        sellDateTime: 'INTEGER',
        sellPrice: 'NUMERIC',
        sellPriceAdjusted: 'NUMERIC',
        sellProceeds: 'NUMERIC',
        sellProceedsAdjusted: 'NUMERIC',
        sellIbCommission: 'NUMERIC',
        sellIbCommissionAdjusted: 'NUMERIC',
        sellNetCashAdjusted: 'NUMERIC',
        sellTxId: 'TEXT',
        pnl: 'NUMERIC',
    },

    timeStamp: {
        timeOfUpdate: 'INTEGER',
        timestamp: 'INTEGER',
        lastTxId: 'TEXT',
    },
}

export default schemaObjects